#ifndef CONFIG_H_
#define CONFIG_H_

#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 800

#define MAX_PARTICLES 1500
#define PARTICLE_VELOCITY 100
#define PARTICLE_RADIUS 2.5f
#define PARTICLE_COLOR YELLOW
#define BACKGROUND_COLOR BLACK

#endif